### ISSUE TITLE
Account for spaces in folders

### ISSUE THREAD

**Issue by tr1s** [qweasd1/hyper-drop-file#1]
Works nice, thanks.

I would be better if it automatically detected the spaces in folder names and insert the appropriate characters to make it work. See both pics for reference (white is terminal, black is hyper)

<img width="447" alt="CleanShot 2020-01-13 at 12 17 42@2x" src="https://user-images.githubusercontent.com/19172250/72276801-c158a980-35fe-11ea-8011-6b4937200fef.png">

<img width="454" alt="CleanShot 2020-01-13 at 12 19 48@2x" src="https://user-images.githubusercontent.com/19172250/72276932-0381eb00-35ff-11ea-8055-85107e10d78d.png">

**Comment by qweasd1** [comment]
nice catch, fix it already. you can update this plugin and restart the terminal and try again! Let me know whether it works and I will close the issue. Also help me a star on this project if you like it!

**Comment by tr1s** [comment]
Yup it worked, thanks!
