### ISSUE TITLE
Support for WSL

### ISSUE THREAD

**Issue by hsusanoo** [qweasd1/hyper-drop-file#6]
The following : 

```
cd C:\Users\usr1\Desktop
```

Should be changed to :

```
cd /mnt/c/users/usr1/Desktop
```

**Comment by qweasd1** [comment]
Hi @hsusanoo 
Thanks for your query.  I change the plugin to add a configuration section to let user define their own path rewrite logic in .hyper.js file. You can put your logic there.(read how to do this in README.md file). x22x22 already write some rewrite logic you can reference from here: https://github.com/qweasd1/hyper-drop-file/pull/5/commits/757cfcbb35871cdbabe35a52931362045afdc854.  Also, don't forgot to escape the whitespace when you rewrite the path.! Let me know your thought and I can close this issue

**Comment by hsusanoo** [comment]
Thanks ! it's definitely better this way !
